services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins Web UI
      - "50000:50000"  # JNLP port for Kubernetes agent
    environment:
      - JAVA_OPTS=-Djenkins.slaves.jnlpHost=host.docker.internal -Djenkins.url=http://host.docker.internal:8080
    volumes:
      - ./jenkins-data:/var/jenkins_home
